### ISSUE TITLE
How Custom Queries Work ?

### ISSUE THREAD

**Issue by Suleman-Elahi** [yuanqing/cuba#2]
![image](https://user-images.githubusercontent.com/24384996/57769192-ea9cff00-772a-11e9-9201-e44e68fdbcf6.png)

**Comment by yuanqing** [comment]
Thanks for reporting. There seems to be bug with the CLI

**Comment by yuanqing** [comment]
@Suleman-Elahi 

It turns out that we can’t use the spreadsheet’s column “labels” when querying a Google Spreadsheet; we need to use the column identifiers. From [the API docs](https://developers.google.com/chart/interactive/docs/querylanguage#select):

> Columns are referenced by the identifiers (not by labels). For example, in a Google Spreadsheet, column identifiers are the one or two character column letter (A, B, C, ...).

So, using [the example spreadsheet](https://docs.google.com/spreadsheets/d/1InLekepCq4XgInfMueA2E2bqDqICVHHTXd_QZab0AOU/edit#gid=0) referenced in the README, we can do the following using the CLI:

```sh
$ cuba 'select A, B' -i 1InLekepCq4XgInfMueA2E2bqDqICVHHTXd_QZab0AOU -n Sheet1
[
  {
    "id": 1,
    "name": "foo"
  },
  {
    "id": 2,
    "name": "bar"
  },
  {
    "id": 3,
    "name": "baz"
  }
]
```
